name: Build and push charts
on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
      - ".github/workflows/build_and_push_chart.yaml"

env:
  REGISTRY: europe-north1-docker.pkg.dev
  CHART: hahaha
  GOOGLE_SA_USER: gh-hahaha

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.6.0"
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "${{ env.GOOGLE_SA_USER }}@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Log in to Google Artifact Registry"
        run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://${{ env.REGISTRY }}
      - uses: azure/setup-helm@v3
        name: "Setup Helm"
        with:
          version: "3.10.0"

      - name: Build Chart
        run: |-
          helm package charts/${{ env.CHART }}
      - name: Push Chart
        run: |-
          helm push ${{ env.CHART }}*.tgz oci://${{ env.REGISTRY }}/nais-io/nais
